default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock
  # host: 127.0.0.1
  # port: 3306

development:
  <<: *default
  database: knowledge_sharing_dev

test:
  <<: *default
  database: knowledge_sharing_test

production:
  <<: *default
  database: knowledge_sharing_pro
